version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www
      - ./conf.d/:/etc/nginx/conf.d/
    ports:
      - 81:80
    depends_on:
      - app
    links:
      - app:app
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"